#!/bin/sh

stable="no"
graphite="no"

usage() {
    printf "Usage: $0 -h,-s\n\n"
    printf "    -h :    Print this help message.\n\n"
    printf "    -s :    Build stable toolchain.\n\n"
    printf "    -g :    Enable 'graphite' USE for gcc.\n\n"
}

while getopts "sgh" params; do
    case $params in
        s)  stable="yes";;
        g)  graphite="yes";;
        h)  usage
            exit;;
    esac
done

if [ "$1"x = "x" ]; then
    usage
    exit 1
fi

TARGETS="x86_64-w64-mingw32 i686-w64-mingw32"

# build_toolchain target ("yes" for graphite) ("yes" for stable)
build_toolchain() {
    TARGET=$1

    GCC_GRAPHITE="no"
    CROSSDEV_CMD="crossdev"

    if [ "$2"x = "yes"x ]; then
        GCC_GRAPHITE="yes"
    fi

    if [ "$3"x = "yes"x ]; then
        CROSSDEV_CMD="crossdev -S -libc ~7.0.0"
    fi

    # Create initial toolchain
    $CROSSDEV_CMD -t $TARGET

    # Disable sjlj for 32bit, but enable dwarf2.
    # (Extra performance for 32bit DXVK)
    if [ $TARGET = "i686-w64-mingw32" ]; then
        GCC_ENV="EXTRA_ECONF=\"--enable-threads=posix"
        GCC_ENV="$GCC_ENV --disable-sjlj-exceptions --with-dwarf2\""
    else
        GCC_ENV="EXTRA_ECONF=\"--enable-threads=posix\""
    fi

    # If GCC_GRAPHITE is 'yes' then enable the graphite USE for gcc
    if [ $GCC_GRAPHITE = "yes" ]; then
        GCC_USE="USE=\"graphite\""
    else
        GCC_USE=""
    fi

    # Enable 'libraries' for mingw64-runtime, and enable threading in gcc.
    $CROSSDEV_CMD --lenv 'USE="libraries"' \
        --genv "$GCC_USE $GCC_ENV" --init-target -t $TARGET

    # Rebuild mingw64-runtime with libraries USE
    emerge -1 --quiet-build y cross-$TARGET/mingw64-runtime

    # Rebuild gcc with threading.
    emerge -1 --quiet-build y cross-$TARGET/gcc
}

for x in $TARGETS; do
    build_toolchain $x $graphite $stable
done
