#!/bin/sh

usage() {
    echo "Usage: # $0 <options>"
    echo
    echo "    -h:  Print this message."
    echo
    echo "    --unstable:  Build toolchain using the latest versions"
    echo "                 of binutils/mingw64-runtime/gcc."
    echo "                 (We'll also apply a patch to fix DXVK and binutils 2.34)"
    echo
    echo "    --crossdev-opts \"options\":  Custom options for crossdev."
    echo "                                  Ex: <# $0 --crossdev-opts \"-S --libc ~7.0.0\">"
}

unset UNSTABLE
unset CROSSDEV_OPTS

# Parse arguments
if [ $1 = "-h" ]; then
    usage
    exit
elif [ $1 = "--unstable" ]; then
    UNSTABLE="yes"
elif [ $1 = "--crossdev-opts" ]; then
    CROSSDEV_OPTS="$2"
elif ! [ -z $1 ]; then
    echo "$1 Option not found"
    echo
    usage
    exit
fi

cleanup() {
    echo "Cleaning files from previous runs from this script."

    rm -v /etc/portage/env/mingw_pthreads
    rm -v /etc/portage/env/mingw_pthreads_dwarf2
    rm -v /etc/portage/package.use/mingw64-runtime-libraries
    rm -v /etc/portage/package.env/mingw-gcc
}

binutils_patch() {
    APPLY="no"
    if [ $UNSTABLE = "yes" ]; then
        APPLY="yes"
    elif ! [ -z $CROSSDEV_OPTS ]; then
        # Assume 2.34 is binutils
        case "$CROSSDEV_OPTS" in
            *2.34*) APPLY="yes" ;;
        esac
    fi

    if [ $APPLY = "yes" ]; then
        echo "Creating /etc/portage/patches/cross-x86_64-w64-mingw32/binutils-2.34"
        mkdir -pv "/etc/portage/patches/cross-x86_64-w64-mingw32/binutils-2.34"

        echo "Symlinking /etc/portage/patches/cross-i686-w64-mingw32 to cross-x86_64-w64-mingw32"
        ln -sfv "/etc/portage/patches/cross-x86_64-w64-mingw32" \
            "/etc/portage/patches/cross-i686-w64-mingw32"

        echo "Downloading binutils 2.34 patch"
        wget "https://sourceware.org/bugzilla/attachment.cgi?id=12545&format=raw" \
            -O "/etc/portage/patches/cross-x86_64-w64-mingw32/binutils-2.34/fix-dxvk-crash.patch"
    else
        echo "Skipping binutils 2.34 patch"
    fi
}

run_crossdev() {
    if [ -z $CROSSDEV_OPTS ]; then
        if [ $UNSTABLE = "yes" ]; then
            CROSSDEV_OPTS=""
        else
            CROSSDEV_OPTS="-S --libc ~7.0.0"
        fi
    fi

    echo "\nRunning 'crossdev $CROSSDEV_OPTS -t x86_64-w64-mingw32'"
    crossdev "$CROSSDEV_OPTS" -t x86_64-w64-mingw32 || exit 1
    echo "\nRunning 'crossdev $CROSSDEV_OPTS -t i686-w64-mingw32'"
    crossdev "$CROSSDEV_OPTS" -t i686-w64-mingw32 || exit 1
}

portage_config() {
    echo
    echo "Adding pthread settings to /etc/portage/env/mingw_pthreads."
    echo "EXTRA_ECONF=\"--enable-threads=posix\"" > /etc/portage/env/mingw_pthreads

    echo
    echo "Adding pthread and dwarf2 exeption handling settings to /etc/portage/env/mingw_pthreads_dwarf2"
    echo "EXTRA_ECONF=\"--enable-threads=posix --disable-sjlj-exceptions --with-dwarf2\"" > /etc/portage/env/mingw_pthreads_dwarf2

    echo
    echo "Enabling 'mingw_pthreads' for cross-x86_64-w64-mingw32/gcc,"
    echo "and 'mingw_pthreads_dwarf2' for cross-i686-w64-mingw32/gcc."
    echo "cross-x86_64-w64-mingw32/gcc mingw_pthreads" > /etc/portage/package.env/mingw-gcc
    echo "cross-i686-w64-mingw32/gcc mingw_pthreads_dwarf2" >> /etc/portage/package.env/mingw-gcc

    echo
    echo "Enabling 'libraries' useflag for cross-x86_64-w64-mingw32/mingw64-runtime,"
    echo "and cross-i686-w64-mingw32/mingw64-runtime"
    echo "cross-x86_64-w64-mingw32/mingw64-runtime libraries" > /etc/portage/package.use/mingw64-runtime-libraries
    echo "cross-i686-w64-mingw32/mingw64-runtime libraries" >> /etc/portage/package.use/mingw64-runtime-libraries
}

remerge() {
    echo
    echo "Re-emerging mingw64-runtime"

    emerge -1v cross-x86_64-w64-mingw32/mingw64-runtime cross-i686-w64-mingw32/mingw64-runtime || exit 1

    echo
    echo "Re-emerging gcc"

    emerge -1v cross-x86_64-w64-mingw32/gcc cross-i686-w64-mingw32/gcc || exit 1
}

finished_msg() {
    echo
    echo "At this point you should now have x86_64-w64-mingw32-gcc,"
    echo "and i686-w64-mingw32-gcc available."
    echo
    echo "Please verify that 'x86_64-w64-mingw32-gcc -v' contains"
    echo "'--enable-posix=threads', and that 'i686-w64-mingw32-gcc -v' contains"
    echo "'--enable-posix=threads', '--disable-sjlj-exceptions', and '--with-dwarf2'."
}

# Start of Script
cleanup
binutils_patch
run_crossdev
portage_config
remerge
finished_msg
